### ISSUE TITLE
package.json engine

### ISSUE THREAD

**Issue by Naramsim** [PokeAPI/pokeapi.co#10]
Hi, I tried running the new version (#8) but it failed on node8. The new svg dependency uses ```...``` which i think it is not supported by node8.

Maybe we can add an engine field in the package.json https://docs.npmjs.com/files/package.json#engines

With node10 it works.

**Comment by cmmartti** [comment]
Good catch. I didn't think to test it on older versions. I don't see any need to maintain compatibility with older versions of Node, so I'll do what you suggested, and also update the readme with minimum Node version.
