### ISSUE TITLE
Look at deployment on to Firebase

### ISSUE THREAD

**Issue by tdmalone** [PokeAPI/pokeapi.co#13]
Because we're now looking at Firebase for the API hosting (due to issues with Netlify), it would be preferable to deploy the documentation site on to our Firebase account as well.

We could technically have the static site on Netlify and the API on Firebase, but it introduces more moving parts - chiefly a proxy on one of the services, because the doc site & API are on the same domain.

**Comment by Naramsim** [comment]
I made a deployment here: https://pokeapi-static-website.firebaseapp.com/

Do you guys think that we should automate the process of pushing to firebase?

**Comment by Naramsim** [comment]
Also there is still the DO logo, but I think we can fix it when pokeapi.co will point to firebase

**Comment by cmmartti** [comment]
@tdmalone I won't have time to look at this until tomorrow, so someone else can jump on it if they want.

**Comment by Naramsim** [comment]
@tdmalone @cmmartti  The CircleCI + Firebase is ready. Take a look at the two PR in this repo. I opened them this morning
