### ISSUE TITLE
Idea: Cosmetic Features

### ISSUE THREAD

**Issue by ricemashi** [PokeAPI/pokeapi.co#134]
I want to show some of my suggestions regarding this website. Here are the lists of ideas:
- Dark Mode: A toggle button for dark mode 
- Search Bar: Similar to Stripe's search bar
- Design Revamp: A change in ui such as typography and layout

I shall contribute into this project if you think these ideas are relevant to the PokeAPI Community. I will then propose the new design of the website in this issue thread if i have no issue with time.

**Comment by Naramsim** [comment]
Hi @ricemashi, thanks a lot for the ideas. The 1st one is really needed. 

the second one has to be though out well. What would you allow to be searched?

The third might be the most needed one. Right now editing the website is a bit tedious because we have to write HTML. Having something that allows us to write in MD would be better.

**Comment by ricemashi** [comment]
> What would you allow to be searched?

The api documentation specifically, each topic or sub-topic can be instantly navigated. I know you can search it via `ctrl f`, its just another cosmetic feature I have thought of.

> Right now editing the website is a bit tedious because we have to write HTML. Having something that allows us to write in MD would be better. 

Oh yea, I definetly agree with your statement. We could hydrate the website in MDX format if thats the hard case.

**Comment by Naramsim** [comment]
Yeah, the ctrl-f works ok right now. Up to you if you would like to work on it. I won't be able to follow along and review many PR. So you'll be primarily alone doing the work. I know it's not ideal but we lack people who have time to dedicate to the project, including myself as well now.

**Comment by C-Garza** [comment]
I can help review PR's and if you need any questions answered I can try and help out when I have time.

**Comment by ricemashi** [comment]
> Yeah, the ctrl-f works ok right now. Up to you if you would like to work on it. I won't be able to follow along and review many PR. So you'll be primarily alone doing the work. I know it's not ideal but we lack people who have time to dedicate to the project, including myself as well now.

Same here,  just ran across this API Documentation when I was teaching APIs to my brother. I just thought of an idea inspired from other API Documentations! 

And yea, I would also definitely open a PR whenever im available. Thanks for the reply guys, I'll close this issue from now.
