### ISSUE TITLE
Invalid redirect

### ISSUE THREAD

**Issue by ItsZabbs** [PokeAPI/pokeapi.co#151]
When typing in the URL https://pokeapi.co/docs , an invalid redirect occurs.
Instead of being redirected to https://pokeapi.co/docs/v2 , you are redirected to docs/v2 (The browser looks for docs/v2 on the user's machine)
If the issue wasn't understood then this image might help.
![image](https://github.com/PokeAPI/pokeapi.co/assets/74313798/1e7f2308-bf3f-45a4-9542-0d54a6c66ef8)

I'm not that knowledgeable about JS but I think [this line](https://github.com/PokeAPI/pokeapi.co/blob/da44ec8953f5108d3defcb6574859e22c3b18043/static.config.js#L52) is the offending one

**Comment by Naramsim** [comment]
True! Many thanks for it! It could also be the Firebase function we are using. 

Will look into it after the festivities

**Comment by Naramsim** [comment]
This should be fixed
