### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by DigimonTrainer** [PokeAPI/pokeapi.co#157]
The Slack link you provided is not up to date(I clicked it, and it gave me a message that said, "This link is no longer active
To join this workspace, you’ll need to ask the person who originally invited you for a new link."). I am spectacular in HTML Dev and a little bit of Python.

**Comment by Naramsim** [comment]
hi, I pushed a commit fixing it. In the meantime you can go to the pokeapi/pokeapi readme and follow the link specified there.

**Comment by DigimonTrainer** [comment]
Okay! Thanks for the assist!
