### ISSUE TITLE
Add a little more explanation on height and weight

### ISSUE THREAD

**Issue by tdmalone** [PokeAPI/pokeapi.co#19]
From PokeAPI/pokeapi#380:

> When I create a sample request for a pokemon, say Garchomp (445), I get that its weight is stored as 950 (950 what?) and its height 19. Checking bulbapedia and pokemondb, I see that these values should be 95.0 and 1.9 respectively. Evidently, these values are ten times what they should be. This can be seen with other pokemon as well.

While this data comes directly from Veekun and we don't modify it, we could definitely document a little more, particularly the units used. Our documentation currently just says:

> height:  The height of this Pokémon.
> weight: The weight of this Pokémon.

**Comment by triangulum** [comment]
I've added a pull-request (PokeAPI/pokeapi.co#20) to this effect. Happy Hacktoberfest! 🍺

**Comment by encukou** [comment]
FWIW, veekun has short descriptions on all the fields, see: https://github.com/veekun/pokedex/blob/master/pokedex/db/tables.py#L1649

**Comment by tdmalone** [comment]
Closed by #20.

Thanks for pointing that out @encukou - feel free to PR in some additional descriptions if you can find some you think we could use!
