### ISSUE TITLE
Documentation json for Evolution Chains

### ISSUE THREAD

**Issue by Prismik** [PokeAPI/pokeapi.co#32]
In the documentation for Evolution chains, the `GET /api/v2/evolution-chain/{id}/` section displays a JSON as an example (see [this link](https://pokeapi.co/docs/v2.html/#evolution-section)). This JSON contains a format error related to the `evolution_details` node for `Ratticate`.

We can see that the doc says this node should be a `list EvolutionDetail`. However, the JSON displays the node as a regular object (i.e. `{ ... }` instead of `[ { ... } ]`.

**Comment by cmmartti** [comment]
Noted! I believe there a couple of errors like this in the docs. I'll fix it soon.
