### ISSUE TITLE
Google has index'd /about/ so loads 404

### ISSUE THREAD

**Issue by miketricking** [PokeAPI/pokeapi.co#36]
Google has index/cached '/about/' as a page, which if you click on returns 404 as react is looking for /about.html to load the view. I'd suggest removing form google if you can or maybe just doing an OR of the location so it will redirect/load anyway. 

I've forked but thought it would probably be easier to leave the decision up to you guys!

**Comment by Naramsim** [comment]
Is this still happening?

**Comment by cmmartti** [comment]
These pages now redirect to their respective pages (with and without trailing slashes):

- https://pokeapi.co/about/
- https://pokeapi.co/docsv1/
- https://pokeapi.co/docsv2/
