### ISSUE TITLE
An error occurred: "SyntaxError: Unexpected token N in JSON at position 0"

### ISSUE THREAD

**Issue by Kronopt** [PokeAPI/pokeapi.co#41]
JSON explorer in the home page of https://pokeapi.co/ throws this error when calling a non-existent resource (everything that returns a 404 error / null json).

ex:
pokemon/a
item/999999
pokedex/404

**Comment by Naramsim** [comment]
Is this still happening?

**Comment by Kronopt** [comment]
Nope.
It's fixed.
