### ISSUE TITLE
Veekun's link in the about page is correct?

### ISSUE THREAD

**Issue by Kronopt** [PokeAPI/pokeapi.co#42]
https://github.com/PokeAPI/pokeapi.co/blob/b5c28e2e81a634a06c8c6f9636fa235bf096789c/src/pages/about.html.js#L121-L122

I expected to go to [Veekun's](https://veekun.com/) website, but this link goes to eevee's github page

**Comment by cmmartti** [comment]
Eevee is the creator of Veekun, but you're right, that link should really go to github.com/veekun.
