### ISSUE TITLE
Issues with the V2 documentation page

### ISSUE THREAD

**Issue by Kronopt** [PokeAPI/pokeapi.co#45]
There are several issues with the V2 documentation page.
I tried to fix them by myself, I even followed the installation guide and was able to quickly have a local instance of the site running, but I don't know much about node.js, so I got stuck there.

## "Contents" side bar
By using the side bar, we can notice that some links are linking to the wrong resources:
* **Contest Types** links to **Encounter Conditions**
* **Contest Effects** links to **Evolution Triggers**
* **Encounter Conditions** links to **Item Attributes**
* **Evolution Triggers** links to **Pal Park Areas**
* **Pokedexes** links to **Move Ailments**
* **Version Groups** links to **Move Targets**
* **Item Attributes** links to **Natures**
* **Item Fling Effects** links to **Pokémon Forms**
* **Move Ailments** links to nowhere
* **Move Damage Classes** links to nowhere
* **Move Targets** links to nowhere
* **Characteristics** links to nowhere
* **Natures** links to nowhere
* **Pokemon** links to the wrong header (also called 'Pokemon')
* **Pokémon Forms** links to nowhere
* **Pokémon Shapes** links to nowhere
* **Stats** links to nowhere

**Locations** and **Machines** link to nowhere and their children links don't show up at all.

The following resources don't show up in the side bar at all:
* Resource Lists / **Un-named**
* Resource Lists / **Named**
* Utility / **Languages**
* Utility / **Common Models**

The highlight which is supposed to indicate the current section doesn't correctly highlight every resource. Some resources are not highlighted.

## Resource description
Almost all resources have a small description before the `GET` text. I noticed this description is in the respective json in the src/docs/ folder.
For example, the **Berry Flavors** resource has the following description in src/docs/berries.json:
```
Flavors determine whether a Pokémon will benefit or suffer from eating a berry based on their nature. Check out Bulbapedia for greater detail.
```
However, from the resources that have a description in their respective json in src/docs/, some are missing that description in the documentation.
The following are missing the description in the documentation:
* Berries
* Contest Types
* Contest Effects
* Super Contest Effects
* Encounter Conditions
* Encounter Condition Values
* Evolution Triggers
* Generations
* Pokedexes
* Version
* Version Groups
* Item
* Item Attributes
* Item Categories
* Item Fling Effects
* Item Pockets
* Locations
* Location Areas
* Pal Park Areas
* Regions
* Machines
* Moves
* Move Ailments
* Move Battle Styles
* Move Damage Classes
* Move Learn Methods
* Move Targets
* Abilities
* Characteristics
* Egg Groups
* Natures
* Pokeathlon Stats
* Pokemon
* Pokémon Colors
* Pokémon Forms
* Pokémon Habitats
* Pokémon Shapes
* Pokémon Species
* Stats
* Types
* Languages

The following have no small description at all (not in the documentation and not in the src/docs/*.json):
* Un-named
* Named
* Berry Firmnesses
* Common Models

## GET

Contest Types shows `GET /api/v2/berry-firmness/{id or name}/` over the correct `GET` text.

The text `GET /api/v2/<resource_name>/{id or name}/` has different sizes all across the documentation. The following have a smaller size and I think should be changed to match the others:
* Berries
* Berry Firmness
* Contest Effects
* Encounter Conditions
* Evolution Triggers
* Pokedexes
* Version Groups
* Item Attributes
* Item Fling Effects
* Locations
* Pal Park Areas
* Machines
* Move Ailments
* Move Damage Classes
* Move Targets
* Characteristics
* Natures
* Pokemon
* Pokémon Forms
* Pokémon Shapes
* Stats
* Languages

## Sorry for the huge wall of text 😅

**Comment by cmmartti** [comment]
What browser are you using? These issues are not because of missing data, but of some weird mix-up that's happening between different object keys. I can't reproduce the errors.

The only data errors are the missing Berry description (it was also missing on the old website) and the fact that Un-named/Named/Language/Common Models are missing from the table of contents widget.

In any case, it's all academic because the page needs to be re-written so that it's not sending the full HTML _and_ all of the JSON _and_ the entire markdown parser down the wire, then re-parsing the JSON and markdown whenever the component re-renders (some of the descriptions use markdown links). That's why that page is so slow to load relative to other pages on the site. I'll have to think about how to do it so all of this happens in Gatsby's build step.

**Comment by Kronopt** [comment]
I'm using Chrome v71.
I tested Edge right now and the same issues occur.
I'm also on Windows 10 right now.

I assumed it was some kind of mix up. The only actual missing data I found was the description of Berry Firmnesses (I also assumed Un-named, Named and Common Models were not worthy of a description and that's why they don't have it, but reported it either way)

**Comment by cmmartti** [comment]
Huh. That's weird. I can only assume it's a caching issue, perhaps with Cloudflare. Are the errors also present at https://pokeapi-co.netlify.com/docs/v2.html?

**Comment by Kronopt** [comment]
Yes, the errors are also present on that site.
Tried with chrome for Android now

**Comment by Naramsim** [comment]
Is this still happening?

**Comment by Kronopt** [comment]
Yes

**Comment by Kronopt** [comment]
Ok, I've reviewed everything using chrome v71 on Windows.

## "Contents" side bar
Almost every link has been fixed. The following are still bugged and all link to the top of the page:
* Pokémon Colors
* Pokémon Forms
* Pokémon Habitats
* Pokémon Shapes
* Pokémon Species

I still think the following should also be on the side bar:
* Resource Lists / Un-named
* Resource Lists / Named
* Utility / Languages
* Utility / Common Models

## Resource description
All resources now have a description in the documentation page with the exception of `Berry Firmnesses`, which doesn't have one at all in the json file.
The others I mentioned (`Un-named`, `Named` and `Common Models`) probably don't need one.

Everything else has been fixed
