### ISSUE TITLE
Documentation errors

### ISSUE THREAD

**Issue by cmmartti** [PokeAPI/pokeapi.co#55]
MoveMetaData is missing from the documentation, as discussed in Slack: https://pokeapi.slack.com/archives/C11T7UB1N/p1551302419004400

You can view it in the old website at https://web.archive.org/web/20180626071935/https://pokeapi.co/docsv2/#movemetadata.

**Comment by FM1337** [comment]
It should also be noted that certain fields in the table describing each field of the json on certain endpoints report incorrect information as well.

An example is PastMoveStatValue's accuracy, it should be of type integer, but instead it reports it as type PastMoveStatValue

**Comment by cmmartti** [comment]
PokemonSpecies also has incorrect descriptions for order and gender_rate.

**Comment by infamoussabre** [comment]
MoveMetaData has incorrect descriptions for: accuracy, effect_chance, pp, priority, power, contest_combos, contest_type

**Comment by HoLLy-HaCKeR** [comment]
Closed by #57?
