### ISSUE TITLE
Documentation jump/hash links regenerate incorrectly upon browser refresh

### ISSUE THREAD

**Issue by icedCoughfee** [PokeAPI/pokeapi.co#69]
After navigating to a specific documentation breadcrumb and refreshing, the url changes from url#id to url/#id (added forward slash). The elements no longer retain correct id's and consequently the breadcrumb jumplinks no longer work. Appears inconsistent as not all sections are affected. 

 In the image below section/sub-section "Pokemon Shapes" has an id of "item-pockets" and "PokemonSpecies", "itempocket"

https://pokeapi.co/docs/v2.html#pokemon-shapes => https://pokeapi.co/docs/v2.html/#pokemon-shapes

![bad-jumplinks](https://user-images.githubusercontent.com/4544439/70841016-b75b4500-1dcb-11ea-8986-495061e232fd.PNG)

**Comment by Naramsim** [comment]
Close as it's fixed with the new ReactStatic version
