### ISSUE TITLE
Add JSON explorer to the home page

### ISSUE THREAD

**Issue by Naramsim** [PokeAPI/pokeapi.co#7]
It would be nice to add a JSON explorer instead of the current textarea.

https://www.npmjs.com/package/react-json-tree

**Comment by cmmartti** [comment]
Good idea, but I think it's important to be able to view the raw JSON too. Maybe an option to switch back and forth (tabs or a checkbox).

**Comment by sargunv** [comment]
That JSON viewer is pretty cool!

**Comment by cmmartti** [comment]
@Naramsim What do you think of #22? See the demo at https://deploy-preview-22--pokeapi-co.netlify.com/

**Comment by Naramsim** [comment]
Thanks for the demo, I really don't have time to spin up a local demo now! I'll take a look
