### ISSUE TITLE
Incorrect types in documentation

### ISSUE THREAD

**Issue by lunik1** [PokeAPI/pokeapi.co#73]
When putting together my rust wrapper I found some fields whose types are incorrectly documented. Here's a complete list to the best of my knowledge:

- `condition` field of `EncounterConditionValue` should be `NamedAPIResource (EncounterCondition)`, is `list NamedAPIResource (EncounterCondition)`
- `category` field of `Item` should be `NamedAPIResource (ItemCategory)`, is `ItemCategory`
- `pokemon` field of `ItemHolderPokemon` should be `NamedAPIResource (Pokemon)`, is `string`
- `rarity` field of `ItemHolderPokemonVersionDetail` should be `integer`, is `string`
- `items` field of `ItemFlingEffect` should be `list NamedAPIResource (Item)`, is `NamedAPIResource (Item)`
- `language` field of `MoveFlavorText` should be `NamedAPIResource (Language)`, is `list NamedAPIResource (Move)`
- `version_group` field of `MoveFlavorText` should be `NamedAPIResource (VersionGroup)`, is `list NamedAPIResource (Move)`
- `category` field of `MoveMetaData` should be `NamedAPIResource (MoveCategory)`, is `NamedAPIResource (Move)`
- `pokemon_species` field of `PokemonShape` should be `list NamedAPIResource (PokemonSpecies)`, is `list PokemonSpecies`
- `characteristics` field of `Stat` ahould be `list APIResource (Characteristic)`, is `APIResource (Characteristic)`

**Comment by Kronopt** [comment]
✔️ `condition` field of `EncounterConditionValue` should be `NamedAPIResource (EncounterCondition)`
✔️ `category` field of `Item` should be `NamedAPIResource (ItemCategory)`
✔️ `pokemon` field of `ItemHolderPokemon` should be `NamedAPIResource (Pokemon)`
✔️ `rarity` field of `ItemHolderPokemonVersionDetail` should be `integer`
✔️ `items` field of `ItemFlingEffect` should be `list NamedAPIResource (Item)`
✔️ `language` field of `MoveFlavorText` should be `NamedAPIResource (Language)`
✔️ `version_group` field of `MoveFlavorText` should be `NamedAPIResource (VersionGroup)`
✔️ `category` field of `MoveMetaData` should be `NamedAPIResource (MoveCategory)`
✔️ `pokemon_species` field of `PokemonShape` should be `list NamedAPIResource (PokemonSpecies)`
✔️ `characteristics` field of `Stat` should be `list APIResource (Characteristic)`

I can confirm them all.
I will update the documentation later  today
