### ISSUE TITLE
location_area_encounter response doesn't match docs

### ISSUE THREAD

**Issue by GregHilmes** [PokeAPI/pokeapi.co#82]
Looking through some of the other issues, this has been a little bit of a common thread among users, but I've found (yet another) difficulty with this data field.

The docs don't match what the API gives as a response. For example, take Butterfree.
 - Lookup [butterfree](https://pokeapi.co/api/v2/pokemon/12/).
 - The value for `location_area_encounters` is `/api/v2/pokemon/12/encounters` (this has already been brought up in PokeAPI/pokeapi#270).
 - The [docs](https://pokeapi.co/docsv2/#pokemon) say that `location_area_encounters` should be an array/list of `location_area`s, each having a name and a url.

I saw from PokeAPI/pokeapi#332 that the url (instead of an array) was implemented as a temp fix, but could the docs be update to reflect this change? The other thing I'm wondering, is what is the planned future of this endpoint/data? I want to know how my code should handle the server's response. It seems like the intended behavior is ambiguous here, and I'm hoping we can get a definite answer for what's wanted and implement it everywhere, docs & all.

**Comment by Naramsim** [comment]
Just checked, the docs were updated. Feel free to reopen if you think more info is needed.
