### ISSUE TITLE
add is_legendary and is_mythical

### ISSUE THREAD

**Issue by Naramsim** [PokeAPI/pokeapi.co#86]
We offer two new properties, those should be added to the docs. 

https://pokeapi.co/api/v2/pokemon-species/129/ `.is_legendary`
https://pokeapi.co/api/v2/pokemon-species/129/ `.is_mythical`

~~_(We should also update the JSON of the `.sprites` of the pokemon endpoint)_~~

**Comment by troyfitzwater** [comment]
Hey there! I wouldn't mind adding these in. After poking around in the docs, it looks like these should be added in between "is_baby" and "hatch_counter" for "Pokemon Species" and "responseModels" in [this](https://github.com/PokeAPI/pokeapi.co/blob/master/src/docs/pokemon.json) file?

**Comment by Naramsim** [comment]
Yep! Basically at~ these lines: 

https://github.com/PokeAPI/pokeapi.co/blob/e46f9e0f1ac2f301ee93784f6c3c678e8a64cfea/src/docs/pokemon.json#L1586

**Comment by troyfitzwater** [comment]
Gotcha, I can take care of that. The only thinkg I'm unsure of is what you mean about updating the `.sprites`

**Comment by Naramsim** [comment]
Ah, forgot about it. I've already taken care about it :)
