### ISSUE TITLE
RealmIO Database

### ISSUE THREAD

**Issue by BrianCorbin** [PokeAPI/pokeapi.co#93]
Hey, so over the past week I've been working on a little sub project of a larger one and was wondering what everyone's thoughts on it were... I scraped all of the v2 csv data and parsed it into a Realm Database with all appropriate linkages to associated fields. I did this for a few reasons...

1. I wanted to have a completely locally hosted instance of the entire pokeAPI data source so I wasn't dependent on making API calls (not having internet would suck)
2. I wanted to create an interface layer on top of that which would make it super easy and super fast to get all relevant data instead of having to send new API calls for sub data (which was solved with RealmIO's relationship models)
3. I was bored and thought it might be cool and useful for anyone else that didn't want to rely on making network calls

Anyways, would be happy to upload the current instance of realmDB files and all Class definitions (currently ONLY written in swift), but wanted to ask about it all first :)

<img width="1670" alt="Screen Shot 2021-01-30 at 12 49 20 PM" src="https://user-images.githubusercontent.com/4346395/106363939-a59f6e80-62f9-11eb-9d9e-1edc6522e641.png">

**Comment by Naramsim** [comment]
Hi @BrianCorbin,

Github issues are not the best way to discuss these topics, but to be honest I don't look anymore at our Slack workspace so you might have posted it there but no one could have seen it. So ok to post here.

First of all our API is based on top of a PostgreSQL DB which users can easily build themselves. I was thinking of creating a Docker image comprehensive of all the data and link it to a PGAdmin. Which is similar to what you've done. Also, I don't know what's RealmIO. Could you tell me the advantages of offering our developers data through RealIO and not PostgreSQL?

If you like you could open-source your solution as well 😄

**Comment by BrianCorbin** [comment]
Ah very cool! I would be happy to open source it once it's finished up :) Few things I wanted to finish fixing.

As far as advantages, RealmIO has a fantastic API for app development with the ability to create links between different tables via class definitions, so it allows you to perform queries on related objects without the need to write your own queries or write any implementation to objectify the data. I find it mostly useful for mobile development, which is what I'm using it for, but Realm provides API support for a ton of languages.

I suppose it's mostly just an alternative to using SQL, as it's built on top of MongoDB and targeted specifically for mobile development.

Here's a link to the site if you (or anyone) are interested https://realm.io/

:)

**Comment by Naramsim** [comment]
Stale, closing
